"""social admin automation foundation

Revision ID: 20260613_0027
Revises: 20260613_0026
Create Date: 2026-06-13
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260613_0027"
down_revision = "20260613_0026"
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.create_table("conversation_context_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("shop_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("shops.id", ondelete="CASCADE"), nullable=False), sa.Column("conversation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False), sa.Column("provider", sa.String(32), nullable=False), sa.Column("channel_account_id", sa.String(128)), sa.Column("item_type", sa.String(64), nullable=False), sa.Column("source_message_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("messages.id", ondelete="SET NULL")), sa.Column("external_reference_id", sa.String(255)), sa.Column("external_url", sa.Text()), sa.Column("title", sa.String(255)), sa.Column("text", sa.Text()), sa.Column("media_json", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("candidate_product_ids_json", postgresql.JSONB(), nullable=False, server_default="[]"), sa.Column("selected_product_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("products.id", ondelete="SET NULL")), sa.Column("selected_variant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("product_variants.id", ondelete="SET NULL")), sa.Column("attributes_json", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("confidence", sa.Numeric(5,4), nullable=False, server_default="1"), sa.Column("expires_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    for c in ["shop_id","conversation_id","provider","channel_account_id","item_type","source_message_id","external_reference_id","selected_product_id","selected_variant_id","expires_at","created_at"]: op.create_index(f"ix_context_items_{c}", "conversation_context_items", [c])
    op.create_table("conversation_reference_links", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("shop_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("shops.id", ondelete="CASCADE"), nullable=False), sa.Column("conversation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False), sa.Column("from_message_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("messages.id", ondelete="CASCADE"), nullable=False), sa.Column("to_context_item_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("conversation_context_items.id", ondelete="CASCADE"), nullable=False), sa.Column("relation_type", sa.String(64), nullable=False), sa.Column("confidence", sa.Numeric(5,4), nullable=False, server_default="1"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    for c in ["shop_id","conversation_id","from_message_id","to_context_item_id","relation_type","created_at"]: op.create_index(f"ix_reference_links_{c}", "conversation_reference_links", [c])
    op.create_table("admin_tasks", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("shop_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("shops.id", ondelete="CASCADE"), nullable=False), sa.Column("requested_by_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("task_type", sa.String(64), nullable=False), sa.Column("input_json", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("output_json", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("status", sa.String(32), nullable=False, server_default="pending"), sa.Column("requires_approval", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("approved_by_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("operator_corrections", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("shop_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("shops.id", ondelete="CASCADE"), nullable=False), sa.Column("conversation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False), sa.Column("message_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("messages.id", ondelete="SET NULL")), sa.Column("correction_type", sa.String(64), nullable=False), sa.Column("before_json", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("after_json", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("operator_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("automation_rule_suggestions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("shop_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("shops.id", ondelete="CASCADE"), nullable=False), sa.Column("source_correction_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("operator_corrections.id", ondelete="SET NULL")), sa.Column("suggested_rule_json", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("status", sa.String(32), nullable=False, server_default="pending"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))

def downgrade() -> None:
    op.drop_table("automation_rule_suggestions"); op.drop_table("operator_corrections"); op.drop_table("admin_tasks"); op.drop_table("conversation_reference_links"); op.drop_table("conversation_context_items")
