import { FormEvent, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';

import { ConfirmDialog } from '../components/ConfirmDialog';
import { ShopSelector } from '../components/ShopSelector';
import { useShop } from '../contexts/ShopContext';
import { useToast } from '../contexts/ToastContext';
import { apiClient } from '../services/apiClient';
import type { RecoveryRule } from '../types/sprintD';

const DEFAULT_TEMPLATE =
  'Hi {customer_name}, your order ({order_total} {currency}) is waiting for payment. Reply here if you need help.';

const TEMPLATE_TOKENS = [
  '{customer_name}',
  '{order_total}',
  '{currency}',
  '{order_id}',
] as const;

const TIMING_PRESETS = [
  { label: '30 min', minutes: 30 },
  { label: '1 hour', minutes: 60 },
  { label: '2 hours', minutes: 120 },
  { label: '6 hours', minutes: 360 },
] as const;

function previewTemplate(template: string): string {
  return template
    .replace('{customer_name}', 'Sara')
    .replace('{order_total}', '49.99')
    .replace('{currency}', 'USD')
    .replace('{order_id}', 'a1b2c3d4');
}

function formatTiming(minutes: number): string {
  if (minutes < 60) {
    return `${minutes} min`;
  }
  if (minutes % 60 === 0) {
    return `${minutes / 60} hr`;
  }
  return `${minutes} min`;
}

export function RecoveryRulesPage() {
  const { selectedShopId } = useShop();
  const { showToast } = useToast();
  const queryClient = useQueryClient();

  const rules = useQuery({
    queryKey: ['recovery-rules', selectedShopId],
    queryFn: () => apiClient.listRecoveryRules(selectedShopId),
    enabled: Boolean(selectedShopId),
  });

  const [triggerAfterMinutes, setTriggerAfterMinutes] = useState(60);
  const [maxAttempts, setMaxAttempts] = useState(3);
  const [messageTemplate, setMessageTemplate] = useState(DEFAULT_TEMPLATE);
  const [onlyInsideWindow, setOnlyInsideWindow] = useState(true);
  const [deleteTarget, setDeleteTarget] = useState<RecoveryRule | null>(null);

  const activeCount = useMemo(
    () => (rules.data ?? []).filter((rule) => rule.is_active).length,
    [rules.data],
  );

  const create = useMutation({
    mutationFn: () =>
      apiClient.createRecoveryRule(selectedShopId, {
        trigger_after_minutes: triggerAfterMinutes,
        max_attempts: maxAttempts,
        message_template: messageTemplate.trim(),
        only_inside_allowed_messaging_window: onlyInsideWindow,
        is_active: true,
      }),
    onSuccess: () => {
      showToast('Recovery rule created.', 'success');
      queryClient.invalidateQueries({ queryKey: ['recovery-rules', selectedShopId] });
    },
    onError: (error) =>
      showToast(error instanceof Error ? error.message : 'Failed to create rule', 'error'),
  });

  const toggleActive = useMutation({
    mutationFn: ({ ruleId, isActive }: { ruleId: string; isActive: boolean }) =>
      apiClient.updateRecoveryRule(selectedShopId, ruleId, { is_active: isActive }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['recovery-rules', selectedShopId] });
    },
    onError: (error) =>
      showToast(error instanceof Error ? error.message : 'Failed to update rule', 'error'),
  });

  const remove = useMutation({
    mutationFn: (ruleId: string) => apiClient.deleteRecoveryRule(selectedShopId, ruleId),
    onSuccess: () => {
      showToast('Recovery rule deleted.', 'success');
      setDeleteTarget(null);
      queryClient.invalidateQueries({ queryKey: ['recovery-rules', selectedShopId] });
    },
    onError: (error) =>
      showToast(error instanceof Error ? error.message : 'Failed to delete rule', 'error'),
  });

  function appendToken(token: string) {
    setMessageTemplate((current) => (current.trim() ? `${current.trim()} ${token}` : token));
  }

  function resetForm() {
    setTriggerAfterMinutes(60);
    setMaxAttempts(3);
    setMessageTemplate(DEFAULT_TEMPLATE);
    setOnlyInsideWindow(true);
  }

  function submit(event: FormEvent) {
    event.preventDefault();
    if (!selectedShopId) {
      showToast('Select a shop first.', 'error');
      return;
    }
    if (!messageTemplate.trim()) {
      showToast('Message template cannot be empty.', 'error');
      return;
    }
    create.mutate();
  }

  const canSubmit = Boolean(selectedShopId && messageTemplate.trim() && !create.isPending);

  return (
    <div className="page-stack page-stack--wide">
      <section className="dashboard-card dashboard-card--wide">
        <p className="dashboard-card__eyebrow">Revenue recovery</p>
        <h1>Abandoned recovery rules</h1>
        <p>
          Send template-based payment reminders when orders stay in waiting-for-payment. Messages are
          never generated by the LLM.
        </p>
        <ShopSelector />
      </section>

      <section className="dashboard-card dashboard-card--wide">
        <h2>Create recovery rule</h2>
        <p className="analytics-toolbar__summary">
          The scheduler marks eligible unpaid orders, then sends your template if channel policy allows.
          Only the newest active rule is used per shop.
        </p>

        {!selectedShopId ? (
          <p className="empty-state">Select a shop to configure recovery rules.</p>
        ) : (
          <form className="trigger-rules-form" onSubmit={submit}>
            <div className="filter-grid">
              <label className="form-field">
                <span>Trigger after (minutes)</span>
                <input
                  type="number"
                  min={1}
                  max={10080}
                  value={triggerAfterMinutes}
                  onChange={(event) => setTriggerAfterMinutes(Number(event.target.value))}
                  required
                />
              </label>

              <label className="form-field">
                <span>Max attempts</span>
                <input
                  type="number"
                  min={1}
                  max={10}
                  value={maxAttempts}
                  onChange={(event) => setMaxAttempts(Number(event.target.value))}
                  required
                />
              </label>
            </div>

            <div className="form-field trigger-rules-form__examples">
              <span>Quick timing presets</span>
              <div className="filter-chips" role="group" aria-label="Timing presets">
                {TIMING_PRESETS.map((preset) => (
                  <button
                    key={preset.minutes}
                    type="button"
                    className={`filter-chip${
                      triggerAfterMinutes === preset.minutes ? ' filter-chip--active' : ''
                    }`}
                    aria-pressed={triggerAfterMinutes === preset.minutes}
                    onClick={() => setTriggerAfterMinutes(preset.minutes)}
                  >
                    {preset.label}
                  </button>
                ))}
              </div>
            </div>

            <label className="form-field form-field--wide">
              <span>Message template</span>
              <textarea
                rows={4}
                value={messageTemplate}
                onChange={(event) => setMessageTemplate(event.target.value)}
                placeholder={DEFAULT_TEMPLATE}
                required
              />
            </label>

            <div className="form-field trigger-rules-form__examples">
              <span>Insert template variables</span>
              <div className="filter-chips" role="group" aria-label="Template variables">
                {TEMPLATE_TOKENS.map((token) => (
                  <button
                    key={token}
                    type="button"
                    className="filter-chip"
                    onClick={() => appendToken(token)}
                  >
                    {token}
                  </button>
                ))}
              </div>
            </div>

            <label className="form-field form-field--checkbox">
              <input
                type="checkbox"
                checked={onlyInsideWindow}
                onChange={(event) => setOnlyInsideWindow(event.target.checked)}
              />
              <span>Only send inside Instagram 24-hour messaging window</span>
            </label>

            <div className="form-field form-field--wide">
              <span>Preview</span>
              <p className="template-preview">{previewTemplate(messageTemplate.trim() || DEFAULT_TEMPLATE)}</p>
            </div>

            <div className="button-row">
              <button className="button button--primary" type="submit" disabled={!canSubmit}>
                {create.isPending ? 'Creating…' : 'Create recovery rule'}
              </button>
              <button className="button button--ghost-dark" type="button" onClick={resetForm}>
                Reset form
              </button>
            </div>
          </form>
        )}

        {create.error ? (
          <p className="form-error">
            {create.error instanceof Error ? create.error.message : 'Failed to create rule'}
          </p>
        ) : null}
      </section>

      <section className="dashboard-card dashboard-card--wide">
        <div className="section-header">
          <div>
            <h2>Configured rules</h2>
            <p className="analytics-toolbar__summary">
              {activeCount} active · {(rules.data?.length ?? 0) - activeCount} paused
            </p>
          </div>
        </div>

        {rules.isLoading ? <p className="loading-state">Loading recovery rules...</p> : null}
        {rules.error ? (
          <p className="form-error">
            {rules.error instanceof Error ? rules.error.message : 'Failed to load recovery rules'}
          </p>
        ) : null}

        <div className="table-wrap">
          <table className="data-table">
            <thead>
              <tr>
                <th>Timing</th>
                <th>Attempts</th>
                <th>Channel policy</th>
                <th>Template</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {rules.data?.map((rule) => (
                <tr key={rule.id}>
                  <td>{formatTiming(rule.trigger_after_minutes)}</td>
                  <td>{rule.max_attempts}</td>
                  <td>{rule.only_inside_allowed_messaging_window ? '24h window' : 'Always allowed'}</td>
                  <td>
                    <p>{rule.message_template}</p>
                    <p className="analytics-toolbar__summary">
                      Preview: {previewTemplate(rule.message_template)}
                    </p>
                  </td>
                  <td>
                    <span className="status-pill">{rule.is_active ? 'Active' : 'Paused'}</span>
                  </td>
                  <td>
                    <div className="rule-actions">
                      <button
                        className="button button--ghost"
                        type="button"
                        disabled={toggleActive.isPending}
                        onClick={() =>
                          toggleActive.mutate({ ruleId: rule.id, isActive: !rule.is_active })
                        }
                      >
                        {rule.is_active ? 'Pause' : 'Activate'}
                      </button>
                      <button
                        className="button button--ghost"
                        type="button"
                        onClick={() => setDeleteTarget(rule)}
                      >
                        Delete
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {!rules.isLoading && (rules.data?.length ?? 0) === 0 ? (
            <p className="empty-state">No recovery rules yet. Create one above.</p>
          ) : null}
        </div>
      </section>

      <ConfirmDialog
        open={Boolean(deleteTarget)}
        title="Delete recovery rule?"
        message="Customers will no longer receive automated payment reminders from this rule."
        confirmLabel="Delete rule"
        onConfirm={() => deleteTarget && remove.mutate(deleteTarget.id)}
        onCancel={() => setDeleteTarget(null)}
        isLoading={remove.isPending}
      />
    </div>
  );
}
